"""empty message

Revision ID: a8e85bdb0679
Revises: f152fa4cd6d5
Create Date: 2025-10-16 18:19:54.295486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e85bdb0679'
down_revision = 'f152fa4cd6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved',
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['liked'], ['post.id'], ),
    sa.PrimaryKeyConstraint('user_from_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved')
    # ### end Alembic commands ###
