"""empty message

Revision ID: c1334c7f89c3
Revises: 6481859132e4
Create Date: 2025-10-16 17:47:34.892815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1334c7f89c3'
down_revision = '6481859132e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('followers')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('8')
        batch_op.drop_column('phone')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('post_creater_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('post_asignee_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('asignee_id')
        batch_op.drop_column('done')
        batch_op.drop_column('creater_id')
        batch_op.drop_column('label')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('creater_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('asignee_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_asignee_id_fkey', 'user', ['asignee_id'], ['id'])
        batch_op.create_foreign_key('post_creater_id_fkey', 'user', ['creater_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('8', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=512), autoincrement=False, nullable=False))

    op.create_table('followers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('8', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='followers_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='followers_pkey')
    )
    op.drop_table('follower')
    # ### end Alembic commands ###
