"""empty message

Revision ID: f152fa4cd6d5
Revises: 566fbd4c70ff
Create Date: 2025-10-16 17:59:23.799420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f152fa4cd6d5'
down_revision = '566fbd4c70ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=500), nullable=False))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('content')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
